---

supervisor_bin_path: '{{ pyenv_bin_directory }}/supervisord'
supervisorctl_bin_path: '{{ pyenv_bin_directory }}/supervisorctl'

# Install a specific version of Supervisor by setting it here (e.g. '3.3.1').
supervisor_version: latest

# Choose whether to use an init script or systemd unit configuration to start
# Supervisor when it's installed and/or after a system boot.
supervisor_started: yes
supervisor_enabled: yes

supervisor_config_path: /etc/supervisor
supervisor_log_dir: /var/log/supervisor
supervisor_run_dir: /run/daphne

# A list of `program`s Supervisor will control. Example commented out below.
# - name: 'apache'
#   command: apache2ctl -c "ErrorLog /dev/stdout" -DFOREGROUND
#   state: present
#   configuration: |
#     autostart=true
#     autorestart=true
#     startretries=1
#     startsecs=1
#     redirect_stderr=true
#     stderr_logfile=/var/log/apache-err.log
#     stdout_logfile=/var/log/apache-out.log
#     user=root
#     killasgroup=true
#     stopasgroup=true
supervisor_programs:
  - name: daphne
    type: fcgi
    command: '{{ pyenv_bin_directory }}/daphne -u {{ supervisor_run_dir }}/daphne%(process_num)d.sock --fd 0 --access-log - --proxy-headers elite.asgi:application'
    state: present
    configuration: |
      autostart=true
      autorestart=true
      socket=tcp://localhost:8000
      directory={{ working_directory }}{{ repo_directory }}
      numprocs={{ ansible_processor_vcpus }}
      process_name=asgi%(process_num)d
      stdout_logfile={{ supervisor_log_dir }}/asgi.log
      redirect_stderr=true
      environment=SECRET_KEY="{{ lookup('env', 'SECRET_KEY') | regex_replace('%', '%%') }}",DB_NAME="{{ lookup('env', 'DB_NAME') }}",DB_USER="{{ lookup('env', 'DB_USER') }}",DB_PASSWORD="{{ lookup('env', 'DB_PASSWORD') }}",DB_HOST="{{ lookup('env', 'DB_HOST') }}",DB_PORT="{{ lookup('env', 'DB_PORT') }}",REDIS_CLIENTID="{{ lookup('env', 'REDIS_CLIENTID') }}",REDIS_PASSWORD="{{ lookup('env', 'REDIS_PASSWORD') }}",REDIS_PORT="{{ lookup('env', 'REDIS_PORT') }}",REDIS_DB="{{ lookup('env', 'REDIS_DB') }}",MEDIA_ROOT="{{ lookup('env', 'MEDIA_ROOT') }}",STATICFILES_DIRS="{{ lookup('env', 'STATICFILES_DIRS') }}",MAILGUN_API_KEY="{{ lookup('env', 'MAILGUN_API_KEY') }}",STRIPE_API_KEY="{{ lookup('env', 'STRIPE_API_KEY') }}",STRIPE_PUBLIC_KEY="{{ lookup('env', 'STRIPE_PUBLIC_KEY') }}"

supervisor_nodaemon: no

supervisor_user: root
supervisor_password: root

supervisor_unix_http_server_enable: yes
supervisor_unix_http_server_socket_path: /var/run/supervisor.sock
supervisor_unix_http_server_password_protect: yes

supervisor_inet_http_server_enable: no
supervisor_inet_http_server_port: '*:9001'
supervisor_inet_http_server_password_protect: yes
