---

# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew: yes
certbot_auto_renew_user: '{{ ansible_user | default(lookup("env", "USER")) }}'
certbot_auto_renew_hour: 3
certbot_auto_renew_minute: 30
certbot_auto_renew_options: --quiet --no-self-upgrade

# Parameters used when creating new Certbot certs.
certbot_create_if_missing: yes
certbot_create_method: standalone
certbot_admin_email: contact@elite-dodgeball.com

certbot_certs:
  - email: '{{ certbot_admin_email }}'
    domains:
      - '{{ app_name }}.com'
# - email: janedoe@example.com
#   domains:
#     - example1.com
#     - example2.com
# - domains:
#     - example3.com

certbot_create_command: >-
  {{ certbot_script }} certonly --standalone --noninteractive --agree-tos
  --email {{ cert_item.email | default(certbot_admin_email) }}
  -d {{ cert_item.domains | join(',') }}

certbot_create_standalone_stop_services:
  - nginx
  # - apache
  # - varnish

# To install from source (on older OSes or if you need a specific or newer
# version of Certbot), set this variable to `yes` and configure other options.
certbot_install_from_source: no
certbot_repo: https://github.com/certbot/certbot.git
certbot_version: master
certbot_keep_updated: yes

# Where to put Certbot when installing from source.
certbot_dir: /opt/certbot

# EPEL
epel_repo_url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ amazon_linux_package_version }}.noarch.rpm
epel_repo_gpg_key_url: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ amazon_linux_package_version }}
epel_repofile_path: /etc/yum.repos.d/epel.repo
