---

- include_tasks: setup.yml

- include_tasks: initialize.yml
- include_tasks: configure.yml

- name: Enable PostgreSQL service
  service:
    name: '{{ postgresql_daemon }}'
    state: '{{ postgresql_service_state }}'
    enabled: '{{ postgresql_service_enabled }}'

- import_tasks: databases.yml
- import_tasks: users.yml
